name: 💡 Feature Request
description: Feature Request
title: "[Feature Request] <write the title here>"
body:
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true
